# Generated by Django 5.2.12 on 2026-06-09 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='schedules/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_papers', models.PositiveIntegerField(default=0)),
                ('total_tracks', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('day_label', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(max_length=20)),
                ('serial_order', models.PositiveIntegerField(default=0)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('track_session', models.CharField(max_length=50)),
                ('track_name', models.CharField(blank=True, max_length=200)),
                ('paper_title', models.CharField(max_length=500)),
                ('author_name', models.CharField(max_length=300)),
                ('university', models.CharField(blank=True, max_length=300)),
                ('mode', models.CharField(blank=True, max_length=50)),
                ('session_chair', models.CharField(blank=True, max_length=200)),
                ('time_slot', models.CharField(blank=True, max_length=50)),
                ('paper_id', models.CharField(max_length=50)),
                ('track_session_display', models.CharField(max_length=50)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='marksheet.scheduleupload')),
            ],
            options={
                'ordering': ['day', 'track_session', 'serial_order'],
            },
        ),
    ]
