# Generated by Django 5.2.12 on 2026-06-09 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0002_marksheettemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(db_index=True, max_length=200)),
                ('plain_password', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profiles', to='marksheet.scheduleupload')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='TrackDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('day_label', models.CharField(blank=True, max_length=100)),
                ('room', models.CharField(max_length=50)),
                ('track_session', models.CharField(max_length=50)),
                ('track_name', models.CharField(blank=True, max_length=200)),
                ('session_chair', models.CharField(blank=True, max_length=200)),
                ('track_coordinator', models.CharField(blank=True, max_length=200)),
                ('moderator_1', models.CharField(blank=True, max_length=200)),
                ('moderator_2', models.CharField(blank=True, max_length=200)),
                ('moderator_3', models.CharField(blank=True, max_length=200)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_duties', to='marksheet.scheduleupload')),
            ],
            options={
                'ordering': ['day', 'track_session', 'room'],
            },
        ),
        migrations.CreateModel(
            name='PaperEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pres_clarity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('originality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('technical_knowledge', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time_management', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('qa_handling', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('novelty', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('methodology', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('result_validation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('impact', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('paper_quality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('accept', 'ACCEPT'), ('minor', 'MINOR REVISION'), ('reject', 'REJECT')], max_length=10)),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_evaluations', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='marksheet.paper')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('paper', 'evaluator')},
            },
        ),
    ]
