# Generated by Django 5.2.12 on 2026-06-09 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0003_facultyprofile_trackduty_paperevaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paperevaluation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paperevaluation',
            name='last_role',
            field=models.CharField(blank=True, choices=[('moderator2', 'Moderator-2'), ('verifier', 'Verifier'), ('admin', 'Admin')], max_length=12),
        ),
        migrations.AddField(
            model_name='paperevaluation',
            name='moderator_entered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paperevaluation',
            name='verifier_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackduty',
            name='verifier',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='paperevaluation',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paperevaluation',
            name='paper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='marksheet.paper'),
        ),
        migrations.CreateModel(
            name='VerifierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(db_index=True, max_length=200)),
                ('plain_password', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifier_profiles', to='marksheet.scheduleupload')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verifier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='TrackSessionLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('track_session', models.CharField(max_length=50)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_locks', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_locks', to='marksheet.scheduleupload')),
            ],
            options={
                'unique_together': {('schedule', 'day', 'track_session')},
            },
        ),
    ]
